# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fix_image_size": "detection.ipynb",
         "estimate_blur": "detection.ipynb",
         "pretty_blur_map": "detection.ipynb",
         "check_contrast": "detection.ipynb"}

modules = ["export.py"]

doc_url = "https://getiquality.github.io/"

git_url = "https://github.com/AndreasMerentitis/detect-contrast-blurriness-literate/master/"

def custom_doc_links(name): return None
